import { Button, TextField, Typography } from "@mui/material";
import { Box } from "@mui/system";
import { useIsomorphicLayoutEffect } from "framer-motion";
import Head from "next/head"
import Image from "next/image";
import Link from "next/link";
import React, { ReactNode, useEffect, useRef, useState } from "react"

interface Props {
    children: ReactNode;
    title?: string;
    onScroll?: any;
};

export default function Layout({ children }: Props) {
    const navRef: any = useRef(null)

    const [navHeight, setNavHeight] = useState(0)

    useEffect(() => {
        console.log(navRef.current.offHeighH)
        setNavHeight(navRef.current.offHeighH)
    }, [navRef.current])

    return (
        <>
            <Head>
                <title>BUA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />

                <link href="https://fonts.cdnfonts.com/css/gilroy-bold" rel="stylesheet" />
                <link href="https://fonts.cdnfonts.com/css/gilroy-heavy" rel="stylesheet" />
                <link href="https://fonts.cdnfonts.com/css/gilroy-light" rel="stylesheet" />
                <link href="https://fonts.cdnfonts.com/css/gilroy-medium" rel="stylesheet" />
                <link href="https://fonts.cdnfonts.com/css/gilroy-regular" rel="stylesheet" />

            </Head>
            <nav
                ref={navRef}
                style={{
                    // position: "fixed",
                    // top: "0",
                    // left: "0",
                    width: "100vw",
                    zIndex: 10
                }}
            >
                <Box display="flex" flexDirection="row" justifyContent={"space-between"} width="100%" sx={{ backgroundColor: "#0e4d65" }} padding={["1rem", "1rem 6rem"]}>
                    <Box height="4rem" overflow="hidden" border="1px solid red">
                        <img
                            src="https://res.cloudinary.com/dfmoqlbyl/image/upload/v1680450056/Boston%20Academy/boston-urban-academy-banner-logo_orig_1_pqaciq.png"
                            alt={`Young african american boy writing`}
                            style={{
                                objectFit: "cover",
                            }}
                        />
                    </Box>
                    <Box display="flex" gap="3rem" alignItems="center">
                        <Box gap="1rem" display={["none", "flex"]}>
                            <Link href="/">HOME</Link>
                            <Link href="/about">ABOUT</Link>
                            <Link href="/board">BOARD</Link>
                            <Link href="/contact">CONTACT</Link>
                        </Box>
                        <Button variant="contained" sx={{
                            backgroundColor: "#f0ad00",
                            padding: "0.5rem 1rem",
                            lineHeight: "100%",
                            height: "fit-content"
                        }}>
                            DONATE
                        </Button>
                    </Box>
                </Box>
            </nav>
            <main style={{ paddingTop: navHeight }}>
                {children}
            </main>
            <footer style={{ width: "100%", }}>
                <Box sx={{ backgroundColor: "#0e4d65" }} padding={["1rem", "6rem"]} display="flex" flexDirection={"column"} gap="4rem">
                    <Box display="flex" flexDirection="row" justifyContent={"space-between"}>
                        <Box>
                            <Box height="4rem" overflow="hidden" border="1px solid red">
                                <img
                                    src="https://res.cloudinary.com/dfmoqlbyl/image/upload/v1680450056/Boston%20Academy/boston-urban-academy-banner-logo_orig_1_pqaciq.png"
                                    alt={`Young african american boy writing`}
                                    style={{
                                        objectFit: "cover",
                                    }}
                                />
                            </Box>
                            <Typography fontFamily="Gilroy-Bold" fontSize="2rem">
                                Support the cause.<br />
                                Partner with us
                            </Typography>
                            <Button variant="contained" sx={{
                                backgroundColor: "#f0ad00",
                                padding: "0.5rem 1rem",
                                lineHeight: "100%",
                                height: "fit-content"
                            }}>
                                DONATE
                            </Button>
                        </Box>
                        <Box display="flex" gap="4rem">
                            <Box display="flex" flexDirection="column" gap="1rem">
                                <Typography fontFamily="Gilroy-Bold">Site Map</Typography>
                                <Link href="/">Home</Link>
                                <Link href="/">About</Link>
                                <Link href="/">Board</Link>
                                <Link href="/">Contact</Link>
                                <Link href="/">Donate</Link>
                            </Box>
                            <Box display="flex" flexDirection="column" gap="1rem">
                                <Typography fontFamily="Gilroy-Bold">Socials</Typography>
                                <Link href="/">Facebook</Link>
                                <Link href="/">LinkedIn</Link>
                                <Link href="/">Instagram</Link>
                                <Link href="/">Twitter</Link>
                            </Box>
                        </Box>
                        <Box>
                            <Typography>Sign Up for our Newsletter</Typography>
                            <TextField
                                variant="standard"
                                placeholder="Enter your email"
                                sx={{
                                    "&.MuiTextField-root": {
                                        color: "white",
                                        borderColor: "white"
                                    }
                                }}
                            />
                        </Box>
                    </Box>
                    <Box display="flex" justifyContent={"space-between"}>
                        <Typography>bostonurbanacademu2021@gmail.com</Typography>
                        <Typography>(123) XXX-XXXX</Typography>
                        <Typography>© 2022 BUA. All rights reserved.</Typography>
                    </Box>
                </Box>
            </footer>
        </>
    )
}
